/// This file has messages for describing applications

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.3
// source: users/rights/rights.proto

package rights

import (
	applications "github.com/allanger/gitlab-environment-aggregator/models/apps/applications"
	common "github.com/allanger/gitlab-environment-aggregator/models/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessRights int32

const (
	AccessRights_READ   AccessRights = 0
	AccessRights_WRITE  AccessRights = 1
	AccessRights_DELETE AccessRights = 2
)

// Enum value maps for AccessRights.
var (
	AccessRights_name = map[int32]string{
		0: "READ",
		1: "WRITE",
		2: "DELETE",
	}
	AccessRights_value = map[string]int32{
		"READ":   0,
		"WRITE":  1,
		"DELETE": 2,
	}
)

func (x AccessRights) Enum() *AccessRights {
	p := new(AccessRights)
	*p = x
	return p
}

func (x AccessRights) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRights) Descriptor() protoreflect.EnumDescriptor {
	return file_users_rights_rights_proto_enumTypes[0].Descriptor()
}

func (AccessRights) Type() protoreflect.EnumType {
	return &file_users_rights_rights_proto_enumTypes[0]
}

func (x AccessRights) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRights.Descriptor instead.
func (AccessRights) EnumDescriptor() ([]byte, []int) {
	return file_users_rights_rights_proto_rawDescGZIP(), []int{0}
}

type AccessRuleId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AccessRuleId) Reset() {
	*x = AccessRuleId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_rights_rights_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRuleId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRuleId) ProtoMessage() {}

func (x *AccessRuleId) ProtoReflect() protoreflect.Message {
	mi := &file_users_rights_rights_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRuleId.ProtoReflect.Descriptor instead.
func (*AccessRuleId) Descriptor() ([]byte, []int) {
	return file_users_rights_rights_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRuleId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AccessRuleIdAndRight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessRight AccessRights `protobuf:"varint,3,opt,name=accessRight,proto3,enum=users.AccessRights" json:"accessRight,omitempty"`
}

func (x *AccessRuleIdAndRight) Reset() {
	*x = AccessRuleIdAndRight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_rights_rights_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRuleIdAndRight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRuleIdAndRight) ProtoMessage() {}

func (x *AccessRuleIdAndRight) ProtoReflect() protoreflect.Message {
	mi := &file_users_rights_rights_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRuleIdAndRight.ProtoReflect.Descriptor instead.
func (*AccessRuleIdAndRight) Descriptor() ([]byte, []int) {
	return file_users_rights_rights_proto_rawDescGZIP(), []int{1}
}

func (x *AccessRuleIdAndRight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessRuleIdAndRight) GetAccessRight() AccessRights {
	if x != nil {
		return x.AccessRight
	}
	return AccessRights_READ
}

type AccessRuleWithoutId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string       `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ApplicationId string       `protobuf:"bytes,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	AccessRight   AccessRights `protobuf:"varint,3,opt,name=accessRight,proto3,enum=users.AccessRights" json:"accessRight,omitempty"`
}

func (x *AccessRuleWithoutId) Reset() {
	*x = AccessRuleWithoutId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_rights_rights_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRuleWithoutId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRuleWithoutId) ProtoMessage() {}

func (x *AccessRuleWithoutId) ProtoReflect() protoreflect.Message {
	mi := &file_users_rights_rights_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRuleWithoutId.ProtoReflect.Descriptor instead.
func (*AccessRuleWithoutId) Descriptor() ([]byte, []int) {
	return file_users_rights_rights_proto_rawDescGZIP(), []int{2}
}

func (x *AccessRuleWithoutId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessRuleWithoutId) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AccessRuleWithoutId) GetAccessRight() AccessRights {
	if x != nil {
		return x.AccessRight
	}
	return AccessRights_READ
}

type AccessRuleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string       `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ApplicationId string       `protobuf:"bytes,3,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	AccessRight   AccessRights `protobuf:"varint,4,opt,name=accessRight,proto3,enum=users.AccessRights" json:"accessRight,omitempty"`
}

func (x *AccessRuleInfo) Reset() {
	*x = AccessRuleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_rights_rights_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRuleInfo) ProtoMessage() {}

func (x *AccessRuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_users_rights_rights_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRuleInfo.ProtoReflect.Descriptor instead.
func (*AccessRuleInfo) Descriptor() ([]byte, []int) {
	return file_users_rights_rights_proto_rawDescGZIP(), []int{3}
}

func (x *AccessRuleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessRuleInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessRuleInfo) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AccessRuleInfo) GetAccessRight() AccessRights {
	if x != nil {
		return x.AccessRight
	}
	return AccessRights_READ
}

type ListOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId *applications.AppId `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
}

func (x *ListOptions) Reset() {
	*x = ListOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_rights_rights_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptions) ProtoMessage() {}

func (x *ListOptions) ProtoReflect() protoreflect.Message {
	mi := &file_users_rights_rights_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptions.ProtoReflect.Descriptor instead.
func (*ListOptions) Descriptor() ([]byte, []int) {
	return file_users_rights_rights_proto_rawDescGZIP(), []int{4}
}

func (x *ListOptions) GetAppId() *applications.AppId {
	if x != nil {
		return x.AppId
	}
	return nil
}

var File_users_rights_rights_proto protoreflect.FileDescriptor

var file_users_rights_rights_proto_rawDesc = []byte{
	0x0a, 0x19, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x1a, 0x27, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x95, 0x01, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x35, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x22, 0x30, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x41, 0x70, 0x70,
	0x49, 0x64, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x2a, 0x2f, 0x0a, 0x0c, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x32, 0xb0, 0x02, 0x0a, 0x06, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75,
	0x6c, 0x65, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x52, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x1b, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x64,
	0x41, 0x6e, 0x64, 0x52, 0x69, 0x67, 0x68, 0x74, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x15, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x42, 0x42, 0x5a,
	0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x64, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x76, 0x73, 0x70,
	0x6f, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_users_rights_rights_proto_rawDescOnce sync.Once
	file_users_rights_rights_proto_rawDescData = file_users_rights_rights_proto_rawDesc
)

func file_users_rights_rights_proto_rawDescGZIP() []byte {
	file_users_rights_rights_proto_rawDescOnce.Do(func() {
		file_users_rights_rights_proto_rawDescData = protoimpl.X.CompressGZIP(file_users_rights_rights_proto_rawDescData)
	})
	return file_users_rights_rights_proto_rawDescData
}

var file_users_rights_rights_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_users_rights_rights_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_users_rights_rights_proto_goTypes = []interface{}{
	(AccessRights)(0),            // 0: users.AccessRights
	(*AccessRuleId)(nil),         // 1: users.AccessRuleId
	(*AccessRuleIdAndRight)(nil), // 2: users.AccessRuleIdAndRight
	(*AccessRuleWithoutId)(nil),  // 3: users.AccessRuleWithoutId
	(*AccessRuleInfo)(nil),       // 4: users.AccessRuleInfo
	(*ListOptions)(nil),          // 5: users.ListOptions
	(*applications.AppId)(nil),   // 6: apps.AppId
	(*common.EmptyMessage)(nil),  // 7: common.EmptyMessage
}
var file_users_rights_rights_proto_depIdxs = []int32{
	0, // 0: users.AccessRuleIdAndRight.accessRight:type_name -> users.AccessRights
	0, // 1: users.AccessRuleWithoutId.accessRight:type_name -> users.AccessRights
	0, // 2: users.AccessRuleInfo.accessRight:type_name -> users.AccessRights
	6, // 3: users.ListOptions.appId:type_name -> apps.AppId
	3, // 4: users.Rights.Create:input_type -> users.AccessRuleWithoutId
	2, // 5: users.Rights.Update:input_type -> users.AccessRuleIdAndRight
	1, // 6: users.Rights.Delete:input_type -> users.AccessRuleId
	1, // 7: users.Rights.Get:input_type -> users.AccessRuleId
	5, // 8: users.Rights.List:input_type -> users.ListOptions
	4, // 9: users.Rights.Create:output_type -> users.AccessRuleInfo
	2, // 10: users.Rights.Update:output_type -> users.AccessRuleIdAndRight
	7, // 11: users.Rights.Delete:output_type -> common.EmptyMessage
	4, // 12: users.Rights.Get:output_type -> users.AccessRuleInfo
	4, // 13: users.Rights.List:output_type -> users.AccessRuleInfo
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_users_rights_rights_proto_init() }
func file_users_rights_rights_proto_init() {
	if File_users_rights_rights_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_users_rights_rights_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRuleId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_rights_rights_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRuleIdAndRight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_rights_rights_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRuleWithoutId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_rights_rights_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRuleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_rights_rights_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_users_rights_rights_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_rights_rights_proto_goTypes,
		DependencyIndexes: file_users_rights_rights_proto_depIdxs,
		EnumInfos:         file_users_rights_rights_proto_enumTypes,
		MessageInfos:      file_users_rights_rights_proto_msgTypes,
	}.Build()
	File_users_rights_rights_proto = out.File
	file_users_rights_rights_proto_rawDesc = nil
	file_users_rights_rights_proto_goTypes = nil
	file_users_rights_rights_proto_depIdxs = nil
}
